"""Initial migration.

Revision ID: e7d463a2b710
Revises: 
Create Date: 2025-09-18 14:19:38.380004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7d463a2b710'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gas_preis_konfiguration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gas_typ', sa.String(length=50), nullable=False),
    sa.Column('preis_pro_bar_liter', sa.Float(), nullable=False),
    sa.Column('gueltig_ab', sa.DateTime(), nullable=False),
    sa.Column('gueltig_bis', sa.DateTime(), nullable=True),
    sa.Column('ist_aktiv', sa.Boolean(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('erstellt_von', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gas_typ')
    )
    op.create_table('handbefuellungen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_typ', sa.String(length=50), nullable=False),
    sa.Column('material_bezeichnung', sa.String(length=100), nullable=False),
    sa.Column('charge_nummer', sa.String(length=50), nullable=True),
    sa.Column('menge_kg', sa.Float(), nullable=False),
    sa.Column('einheit', sa.String(length=10), nullable=True),
    sa.Column('behaelter_id', sa.String(length=50), nullable=True),
    sa.Column('befuellt_am', sa.DateTime(), nullable=False),
    sa.Column('befuellt_von', sa.String(length=100), nullable=False),
    sa.Column('etikett_gedruckt', sa.Boolean(), nullable=True),
    sa.Column('etikett_nummer', sa.String(length=50), nullable=True),
    sa.Column('temperatur', sa.Float(), nullable=True),
    sa.Column('luftfeuchtigkeit', sa.Float(), nullable=True),
    sa.Column('notizen', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kunden',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mitgliedsnummer', sa.String(length=20), nullable=False),
    sa.Column('externe_kundennummer', sa.String(length=50), nullable=True),
    sa.Column('externe_system', sa.String(length=100), nullable=True),
    sa.Column('vorname', sa.String(length=50), nullable=False),
    sa.Column('nachname', sa.String(length=100), nullable=False),
    sa.Column('firma', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefon', sa.String(length=30), nullable=True),
    sa.Column('strasse', sa.String(length=200), nullable=True),
    sa.Column('plz', sa.String(length=10), nullable=True),
    sa.Column('ort', sa.String(length=100), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('mitglied_seit', sa.Date(), nullable=False),
    sa.Column('mitgliedschaft_typ', sa.String(length=30), nullable=True),
    sa.Column('ist_aktiv', sa.Boolean(), nullable=True),
    sa.Column('notizen', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mitgliedsnummer')
    )
    op.create_table('patrone_einkauf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eingekauft_von', sa.String(length=100), nullable=False),
    sa.Column('einkauf_datum', sa.DateTime(), nullable=False),
    sa.Column('lieferant', sa.String(length=200), nullable=False),
    sa.Column('produkt_name', sa.String(length=200), nullable=False),
    sa.Column('produkt_typ', sa.String(length=50), nullable=False),
    sa.Column('menge', sa.Float(), nullable=False),
    sa.Column('einheit', sa.String(length=20), nullable=False),
    sa.Column('einzelpreis', sa.Float(), nullable=True),
    sa.Column('gesamtpreis', sa.Float(), nullable=True),
    sa.Column('waehrung', sa.String(length=10), nullable=False),
    sa.Column('lieferdatum', sa.DateTime(), nullable=True),
    sa.Column('ist_geliefert', sa.Boolean(), nullable=False),
    sa.Column('charge_nummer_lieferant', sa.String(length=100), nullable=True),
    sa.Column('haltbarkeitsdatum', sa.DateTime(), nullable=True),
    sa.Column('qualitaets_zertifikat', sa.String(length=200), nullable=True),
    sa.Column('kleber_gedruckt', sa.Boolean(), nullable=False),
    sa.Column('kleber_gedruckt_am', sa.DateTime(), nullable=True),
    sa.Column('lagerort', sa.String(length=100), nullable=True),
    sa.Column('verbraucht_menge', sa.Float(), nullable=False),
    sa.Column('verbleibende_menge', sa.Float(), nullable=True),
    sa.Column('ist_aktiv', sa.Boolean(), nullable=False),
    sa.Column('notizen', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patrone_vorbereitung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vorbereitet_von', sa.String(length=100), nullable=False),
    sa.Column('vorbereitet_am', sa.DateTime(), nullable=False),
    sa.Column('patrone_typ', sa.String(length=50), nullable=False),
    sa.Column('patrone_nummer', sa.String(length=20), nullable=True),
    sa.Column('charge_nummer', sa.String(length=50), nullable=False),
    sa.Column('gewicht_vor_fuellen', sa.Float(), nullable=True),
    sa.Column('gewicht_nach_fuellen', sa.Float(), nullable=True),
    sa.Column('material_verwendet', sa.String(length=200), nullable=True),
    sa.Column('ist_bereit', sa.Boolean(), nullable=False),
    sa.Column('ist_verwendet', sa.Boolean(), nullable=False),
    sa.Column('verwendung_datum', sa.DateTime(), nullable=True),
    sa.Column('etikett_gedruckt', sa.Boolean(), nullable=False),
    sa.Column('etikett_gedruckt_am', sa.DateTime(), nullable=True),
    sa.Column('notizen', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patronenwechsel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wechsel_datum', sa.DateTime(), nullable=False),
    sa.Column('durchgefuehrt_von', sa.String(length=100), nullable=False),
    sa.Column('betriebsstunden_bei_wechsel', sa.Float(), nullable=False),
    sa.Column('betriebsstunden_seit_letztem_wechsel', sa.Float(), nullable=False),
    sa.Column('molekularsieb_patrone_1_gewechselt', sa.Boolean(), nullable=False),
    sa.Column('molekularsieb_patrone_2_gewechselt', sa.Boolean(), nullable=False),
    sa.Column('kohle_filter_gewechselt', sa.Boolean(), nullable=False),
    sa.Column('molekularsieb_1_charge', sa.String(length=50), nullable=True),
    sa.Column('molekularsieb_2_charge', sa.String(length=50), nullable=True),
    sa.Column('kohle_filter_charge', sa.String(length=50), nullable=True),
    sa.Column('alte_molekularsieb_1_charge', sa.String(length=50), nullable=True),
    sa.Column('alte_molekularsieb_2_charge', sa.String(length=50), nullable=True),
    sa.Column('alte_kohle_filter_charge', sa.String(length=50), nullable=True),
    sa.Column('notizen', sa.Text(), nullable=True),
    sa.Column('naechster_wechsel_faellig_bei', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patronenwechsel_konfiguration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patronenwechsel_intervall_stunden', sa.Float(), nullable=False),
    sa.Column('warnung_vor_stunden', sa.Float(), nullable=False),
    sa.Column('ist_aktiv', sa.Boolean(), nullable=False),
    sa.Column('erstellt_von', sa.String(length=100), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('printer_konfiguration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('drucker_typ', sa.String(length=50), nullable=False),
    sa.Column('interface_typ', sa.String(length=20), nullable=False),
    sa.Column('verbindung_config', sa.Text(), nullable=True),
    sa.Column('papier_breite_mm', sa.Integer(), nullable=False),
    sa.Column('max_zeichen_pro_zeile', sa.Integer(), nullable=False),
    sa.Column('ist_aktiv', sa.Boolean(), nullable=False),
    sa.Column('ist_standard', sa.Boolean(), nullable=False),
    sa.Column('letzter_test', sa.DateTime(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('erstellt_von', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('vorname', sa.String(length=50), nullable=True),
    sa.Column('nachname', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('wartungen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typ', sa.String(length=50), nullable=False),
    sa.Column('datum', sa.DateTime(), nullable=False),
    sa.Column('durchgefuehrt_von', sa.String(length=100), nullable=False),
    sa.Column('naechste_faellig', sa.DateTime(), nullable=True),
    sa.Column('intervall_tage', sa.Integer(), nullable=True),
    sa.Column('notizen', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wartungsintervall',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_datum', sa.DateTime(), nullable=False),
    sa.Column('reset_grund', sa.String(length=200), nullable=True),
    sa.Column('startstand_stunden', sa.Float(), nullable=False),
    sa.Column('wartungsintervall_stunden', sa.Float(), nullable=False),
    sa.Column('naechste_wartung_bei', sa.Float(), nullable=True),
    sa.Column('ist_aktiv', sa.Boolean(), nullable=False),
    sa.Column('durchgefuehrt_von', sa.String(length=100), nullable=True),
    sa.Column('notizen', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flaschen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flasche_nummer', sa.String(length=50), nullable=False),
    sa.Column('externe_flasche_nummer', sa.String(length=100), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('bauart_zulassung', sa.String(length=100), nullable=True),
    sa.Column('seriennummer', sa.String(length=100), nullable=True),
    sa.Column('herstellungs_datum', sa.Date(), nullable=True),
    sa.Column('interne_flaschennummer_auto', sa.Boolean(), nullable=True),
    sa.Column('barcode_typ', sa.String(length=20), nullable=True),
    sa.Column('letzte_pruefung_protokoll', sa.Text(), nullable=True),
    sa.Column('pruefung_benachrichtigt', sa.Boolean(), nullable=True),
    sa.Column('pruefung_benachrichtigung_datum', sa.Date(), nullable=True),
    sa.Column('flaschen_gewicht_kg', sa.Float(), nullable=True),
    sa.Column('ventil_typ', sa.String(length=50), nullable=True),
    sa.Column('ursprungsland', sa.String(length=50), nullable=True),
    sa.Column('kaufdatum', sa.Date(), nullable=True),
    sa.Column('garantie_bis', sa.Date(), nullable=True),
    sa.Column('externe_referenzen', sa.Text(), nullable=True),
    sa.Column('kunde_id', sa.Integer(), nullable=False),
    sa.Column('groesse_liter', sa.Float(), nullable=False),
    sa.Column('flaschen_typ', sa.String(length=50), nullable=True),
    sa.Column('farbe', sa.String(length=30), nullable=True),
    sa.Column('hersteller', sa.String(length=100), nullable=True),
    sa.Column('pruef_datum', sa.Date(), nullable=True),
    sa.Column('naechste_pruefung', sa.Date(), nullable=True),
    sa.Column('max_druck_bar', sa.Integer(), nullable=True),
    sa.Column('ist_aktiv', sa.Boolean(), nullable=True),
    sa.Column('ist_zum_fuellen_vorgemerkt', sa.Boolean(), nullable=True),
    sa.Column('letzter_fuellstand', sa.Float(), nullable=True),
    sa.Column('notizen', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kunde_id'], ['kunden.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('flasche_nummer')
    )
    op.create_table('fuellvorgaenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_zeit', sa.DateTime(), nullable=False),
    sa.Column('end_zeit', sa.DateTime(), nullable=True),
    sa.Column('dauer_minuten', sa.Integer(), nullable=True),
    sa.Column('operator', sa.String(length=100), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notizen', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kompressor_betrieb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_zeit', sa.DateTime(), nullable=False),
    sa.Column('end_zeit', sa.DateTime(), nullable=True),
    sa.Column('betriebsdauer_minuten', sa.Integer(), nullable=True),
    sa.Column('oel_getestet', sa.Boolean(), nullable=False),
    sa.Column('oel_test_ergebnis', sa.String(length=10), nullable=True),
    sa.Column('oel_tester', sa.String(length=100), nullable=True),
    sa.Column('oel_tester_id', sa.Integer(), nullable=True),
    sa.Column('fueller', sa.String(length=100), nullable=False),
    sa.Column('fueller_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notizen', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fueller_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['oel_tester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patrone_wechsel_protokoll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patronenwechsel_id', sa.Integer(), nullable=False),
    sa.Column('gewechselt_von', sa.String(length=100), nullable=False),
    sa.Column('wechsel_datum', sa.DateTime(), nullable=False),
    sa.Column('vorbereitung_id', sa.Integer(), nullable=True),
    sa.Column('alte_patrone_gewicht', sa.Float(), nullable=True),
    sa.Column('neue_patrone_gewicht', sa.Float(), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=False),
    sa.Column('alte_patrone_zustand', sa.String(length=200), nullable=True),
    sa.Column('wechsel_grund', sa.String(length=200), nullable=True),
    sa.Column('betriebsstunden_alte_patrone', sa.Float(), nullable=True),
    sa.Column('alte_patrone_entsorgt', sa.Boolean(), nullable=False),
    sa.Column('entsorgung_datum', sa.DateTime(), nullable=True),
    sa.Column('entsorgung_art', sa.String(length=100), nullable=True),
    sa.Column('notizen', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patronenwechsel_id'], ['patronenwechsel.id'], ),
    sa.ForeignKeyConstraint(['vorbereitung_id'], ['patrone_vorbereitung.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('print_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_typ', sa.String(length=50), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('erstellt_von', sa.String(length=100), nullable=False),
    sa.Column('patronenwechsel_id', sa.Integer(), nullable=True),
    sa.Column('drucker_id', sa.Integer(), nullable=True),
    sa.Column('etikett_daten', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('druckversuche', sa.Integer(), nullable=False),
    sa.Column('letzter_druckversuch', sa.DateTime(), nullable=True),
    sa.Column('gedruckt_am', sa.DateTime(), nullable=True),
    sa.Column('fehler_nachricht', sa.Text(), nullable=True),
    sa.Column('wiederholungsdrucke', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drucker_id'], ['printer_konfiguration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('printer_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drucker_id', sa.Integer(), nullable=False),
    sa.Column('zeitpunkt', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('nachricht', sa.String(length=255), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['drucker_id'], ['printer_konfiguration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bulk_fuellvorgaenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_zeit', sa.DateTime(), nullable=False),
    sa.Column('end_zeit', sa.DateTime(), nullable=True),
    sa.Column('gesamtdauer_minuten', sa.Integer(), nullable=True),
    sa.Column('operator', sa.String(length=100), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('anzahl_flaschen', sa.Integer(), nullable=False),
    sa.Column('erfolgreich_gefuellt', sa.Integer(), nullable=True),
    sa.Column('fehlgeschlagen', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('kompressor_betrieb_id', sa.Integer(), nullable=True),
    sa.Column('notizen', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kompressor_betrieb_id'], ['kompressor_betrieb.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuellmanager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kunde_id', sa.Integer(), nullable=False),
    sa.Column('flasche_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('auftragsnummer', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('annahme_zeit', sa.DateTime(), nullable=False),
    sa.Column('fuellstart_zeit', sa.DateTime(), nullable=True),
    sa.Column('fuellende_zeit', sa.DateTime(), nullable=True),
    sa.Column('uebergabe_zeit', sa.DateTime(), nullable=True),
    sa.Column('visuelle_pruefung', sa.Boolean(), nullable=True),
    sa.Column('tuev_geprueft', sa.Boolean(), nullable=True),
    sa.Column('ventil_zustand', sa.String(length=20), nullable=True),
    sa.Column('annahme_notizen', sa.Text(), nullable=True),
    sa.Column('restdruck_bar', sa.Float(), nullable=False),
    sa.Column('zieldruck_bar', sa.Float(), nullable=False),
    sa.Column('tatsaechlicher_enddruck', sa.Float(), nullable=True),
    sa.Column('sauerstoff_prozent', sa.Float(), nullable=False),
    sa.Column('helium_prozent', sa.Float(), nullable=False),
    sa.Column('stickstoff_prozent', sa.Float(), nullable=False),
    sa.Column('berechnungen', sa.Text(), nullable=True),
    sa.Column('preis_helium', sa.Float(), nullable=False),
    sa.Column('preis_sauerstoff', sa.Float(), nullable=False),
    sa.Column('preis_luft', sa.Float(), nullable=False),
    sa.Column('gesamtpreis', sa.Float(), nullable=False),
    sa.Column('bezahlt', sa.Boolean(), nullable=True),
    sa.Column('fuell_notizen', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flasche_id'], ['flaschen.id'], ),
    sa.ForeignKeyConstraint(['kunde_id'], ['kunden.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auftragsnummer')
    )
    op.create_table('warteliste_eintraege',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flasche_id', sa.Integer(), nullable=False),
    sa.Column('annahme_datum', sa.Date(), nullable=False),
    sa.Column('gewuenschter_druck', sa.Integer(), nullable=False),
    sa.Column('besonderheiten', sa.Text(), nullable=True),
    sa.Column('prioritaet', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('fueller', sa.String(length=100), nullable=True),
    sa.Column('luftgemisch', sa.String(length=50), nullable=True),
    sa.Column('fuell_start', sa.DateTime(), nullable=True),
    sa.Column('fuell_ende', sa.DateTime(), nullable=True),
    sa.Column('erreichter_druck', sa.Integer(), nullable=True),
    sa.Column('notizen', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flasche_id'], ['flaschen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flasche_fuellvorgang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bulk_fuellvorgang_id', sa.Integer(), nullable=False),
    sa.Column('flasche_id', sa.Integer(), nullable=False),
    sa.Column('ziel_druck', sa.Integer(), nullable=True),
    sa.Column('erreicher_druck', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('gefuellt_um', sa.DateTime(), nullable=True),
    sa.Column('fueller_name', sa.String(length=100), nullable=True),
    sa.Column('kompressor_id', sa.String(length=50), nullable=True),
    sa.Column('fehler_grund', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bulk_fuellvorgang_id'], ['bulk_fuellvorgaenge.id'], ),
    sa.ForeignKeyConstraint(['flasche_id'], ['flaschen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuellmanager_signaturen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fuellmanager_id', sa.Integer(), nullable=False),
    sa.Column('signatur_typ', sa.String(length=20), nullable=False),
    sa.Column('signatur_daten', sa.Text(), nullable=False),
    sa.Column('unterschrieben_am', sa.DateTime(), nullable=False),
    sa.Column('unterschrieben_von', sa.String(length=100), nullable=False),
    sa.Column('device_info', sa.String(length=500), nullable=True),
    sa.Column('ip_adresse', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['fuellmanager_id'], ['fuellmanager.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuellvorgang_erweitert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fuellmanager_id', sa.Integer(), nullable=False),
    sa.Column('ereignis_typ', sa.String(length=50), nullable=False),
    sa.Column('ereignis_zeit', sa.DateTime(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fuellmanager_id'], ['fuellmanager.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fuellvorgang_erweitert')
    op.drop_table('fuellmanager_signaturen')
    op.drop_table('flasche_fuellvorgang')
    op.drop_table('warteliste_eintraege')
    op.drop_table('fuellmanager')
    op.drop_table('bulk_fuellvorgaenge')
    op.drop_table('printer_status')
    op.drop_table('print_jobs')
    op.drop_table('patrone_wechsel_protokoll')
    op.drop_table('kompressor_betrieb')
    op.drop_table('fuellvorgaenge')
    op.drop_table('flaschen')
    op.drop_table('wartungsintervall')
    op.drop_table('wartungen')
    op.drop_table('users')
    op.drop_table('printer_konfiguration')
    op.drop_table('patronenwechsel_konfiguration')
    op.drop_table('patronenwechsel')
    op.drop_table('patrone_vorbereitung')
    op.drop_table('patrone_einkauf')
    op.drop_table('kunden')
    op.drop_table('handbefuellungen')
    op.drop_table('gas_preis_konfiguration')
    # ### end Alembic commands ###
