"""Initial database schema

Revision ID: 04ecc7d05779
Revises: 
Create Date: 2025-06-26 18:42:59.964300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ecc7d05779'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handbefuellungen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_typ', sa.String(length=50), nullable=False),
    sa.Column('material_bezeichnung', sa.String(length=100), nullable=False),
    sa.Column('charge_nummer', sa.String(length=50), nullable=True),
    sa.Column('menge_kg', sa.Float(), nullable=False),
    sa.Column('einheit', sa.String(length=10), nullable=True),
    sa.Column('behaelter_id', sa.String(length=50), nullable=True),
    sa.Column('befuellt_am', sa.DateTime(), nullable=False),
    sa.Column('befuellt_von', sa.String(length=100), nullable=False),
    sa.Column('etikett_gedruckt', sa.Boolean(), nullable=True),
    sa.Column('etikett_nummer', sa.String(length=50), nullable=True),
    sa.Column('temperatur', sa.Float(), nullable=True),
    sa.Column('luftfeuchtigkeit', sa.Float(), nullable=True),
    sa.Column('notizen', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('vorname', sa.String(length=50), nullable=True),
    sa.Column('nachname', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('wartungen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typ', sa.String(length=50), nullable=False),
    sa.Column('datum', sa.DateTime(), nullable=False),
    sa.Column('durchgefuehrt_von', sa.String(length=100), nullable=False),
    sa.Column('naechste_faellig', sa.DateTime(), nullable=True),
    sa.Column('intervall_tage', sa.Integer(), nullable=True),
    sa.Column('notizen', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuellvorgaenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_zeit', sa.DateTime(), nullable=False),
    sa.Column('end_zeit', sa.DateTime(), nullable=True),
    sa.Column('dauer_minuten', sa.Integer(), nullable=True),
    sa.Column('operator', sa.String(length=100), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notizen', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fuellvorgaenge')
    op.drop_table('wartungen')
    op.drop_table('users')
    op.drop_table('handbefuellungen')
    # ### end Alembic commands ###
